"""Incendies table

Revision ID: d6029532daa9
Revises: 
Create Date: 2020-06-03 14:06:45.956976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6029532daa9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incendies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=True),
    sa.Column('position_y', sa.Float(), nullable=True),
    sa.Column('intensite', sa.Integer(), nullable=True),
    sa.Column('categorie', sa.String(length=10), nullable=True),
    sa.Column('detecte', sa.Integer(), nullable=True),
    sa.Column('prise_en_charge', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incendies_categorie'), 'incendies', ['categorie'], unique=False)
    op.create_index(op.f('ix_incendies_detecte'), 'incendies', ['detecte'], unique=False)
    op.create_index(op.f('ix_incendies_intensite'), 'incendies', ['intensite'], unique=False)
    op.create_index(op.f('ix_incendies_position_x'), 'incendies', ['position_x'], unique=False)
    op.create_index(op.f('ix_incendies_position_y'), 'incendies', ['position_y'], unique=False)
    op.create_index(op.f('ix_incendies_prise_en_charge'), 'incendies', ['prise_en_charge'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incendies_prise_en_charge'), table_name='incendies')
    op.drop_index(op.f('ix_incendies_position_y'), table_name='incendies')
    op.drop_index(op.f('ix_incendies_position_x'), table_name='incendies')
    op.drop_index(op.f('ix_incendies_intensite'), table_name='incendies')
    op.drop_index(op.f('ix_incendies_detecte'), table_name='incendies')
    op.drop_index(op.f('ix_incendies_categorie'), table_name='incendies')
    op.drop_table('incendies')
    # ### end Alembic commands ###
